name: Run Postman API Tests (Newman)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman

      - name: Run MusicBrainz Test Collection
        run: newman run https://api.postman.com/collections/4784767-81c74bdd-5f64-4631-b460-a74cf6fd5707?apikey=${{ secrets.POSTMAN_API_KEY }}
